* Centers of Attention: How Joint Attention Solves the Hard Problem of Content

  [WORK IN PROGRESS]

  by Robert P. Levy

** Abstract

   Psychology is on course to becoming a hard science (which is to say
   a general explanatory framwork consistent with physics and biology,
   rather than a patchwork of popular models that each have some
   utility in some domain) but has met with the Hard Problem of
   Content (Hutto & Myin 2013) as one of its most pressing concerns.
   Another relatively newer field that has at various times been
   called computer science, cybernetics, or informatics has been
   stymied by the same problem of meaningfully operating on
   information content, in its quest to move from more narrow and
   literal to more generic and flexibly expressive machinery. Physical
   agents are unproblematically sensitive to pragmatic information
   (tracking causal effects and exploiting causative possibilities),
   but the hard problem is how do some kinds of agents (perhaps only
   humans as of yet) acquire the capacity to traffic in information
   *about* the situations they find themselves in?  In this paper I
   make the case for an ecological-semiotic approach that enriches the
   traditonal Gibsonian approach with a Peircean biosemiotic model of
   convention-based use of ecological information.  A case is made for
   the ecological task as semiotic self-control even in the basic
   case, which joint attention surfaces into a coordinative enterprise
   of publicly iterating and generalizing tasks into practices.  This
   process is identified as the source of public symbol-use and
   content. A formal model of basic and joint agency is presented,
   along with some proposed constructive tests of the hypothesis.

** Outline of Thesis

   + **Ecological Information Basics**

     - **Why ecological psychology?** The Gibsonian ecological
       approach is the the most well-developed and explanatory theory
       of pragmatic information and therefore the most promising
       avenue for offering a coherent and veridical account of
       information and its applications.

     - **Law-based ecological information.** A review of Gibsons's
       theory of perception and ecological information as since
       developed by Turvey and others.

     - **Convention-based use of ecological information.** A review of
       Golonka & Wilson's work on convention-base use of ecological
       information as an explanation of cognition that goes beyond
       strictly direct and perceivable information.

   + **An Ecological-Semiotic Approach to Perception and Information**
     Proposal to merge Biosemiotics and Ecological
     Psychology.

     - **Gibsonian information theory needs Peircean biosemiotics.**
       Gibsonian ecological psychology is enriched by a biosemiotic
       understanding of the convention-based uses of ecological
       information To complete the account of the convention-based
       aspects of pragmatic information-use (semiosis).  Peirce's
       model is highly explanatory of convention-based processes.
       Biosemiotics has found great utility in applying this approach
       to understanding teleological mechanisms in the "wet
       cybernetics" of life.

     - **Peircean Biosemiotics needs a Gibsonian foundation**. It
       tries to build up from sensations, which doesn't work.  this is
       borderline mysticism (in some of the same ways enactivism is as
       well). Gibson's approach solves this.

     - **Semiotic Scaffolding**. A review of Hoffmeyer's biosemiotic
       work on semiotic scaffolding, and Stjernfelt's work on the
       evolution of semioic self-control.

     - **The Prospective Control Task as Semiotic Self-control**

       - The fact that organisms innately depend on detecting
         convention-based information for their basic self-maintenant
         functions reveals that perception-action cycles are couched
         in convention-based semiotic control at the task level.

       - Turvey's ontology of task performance in the 1992 paper
         appears to have independentally identified task performance
         as having a triadic structure

       - Peirce's symbol/semiosis, while intended to be an abstract
         and broadly applicable mathematical fact, is clarified
         greatly if taken to paradigmatically begin as the case of an
         agent attending to a task such that the vehicle is the
         context of it being possible and advisable to engaging the
         task, the intepretant is a context of focus where the
         relevant subtasks are solicited in support of the the task,
         others excluded from focus as not helpful or relevant, and
         the symbol's object or target is the context of having
         realized the task's purpose.  This Gibsonian task
         interpretation of Peircean symbol and vice versa is what I
         have termed a "center of attention".

   + **The Hard Problem of Content**

     - **The problem.** brief overview of Hutto & Myin's argument

     - **Proposed solutions.** no need to rehash the litany of
       approaches that fail as these are mostly covered by Hutto &
       Myin. But I will explore some solutions that fail to solve it
       as way of making the clear the problem we're trying to solve
       and why it's a real problem.

       - Korbak: Skyrms signaling networks solve the hard problem. It
         does not solve it because it only trains agents behaviors
         into alignment with facts of the evironment, it does not not
         inform agents of these facts such they might attend to the
         relevant factors for accessing them.

       - Bickhard: TODO, I have a working suspicion, but I need to
         better understand Bickhard's work in order to be certain.

     - **Joint attention as a solution to the hard problem of
       content** Review prior art, and what it so far does not explain

       - Tomasello: Framework of Cooperative Communication

       - Ramstead et al: Cultural Affordances

       - Stjernfelt: Joint Attention and Semiotic Self-control

   + **An Ecological-Semiotic Approach to Joint Attention**

     + **Clues from empirical research.** Tomasello's research on joint
       attention offers a revealing piece of evidence: the
       human-unique skill set developed in infancy (sharing, following
       into, and directing attention) corresponding to the triadic
       structure of task attention.  I make sense of Tomasello's
       finding as evidence that humans necessarily develop a keen
       awareness and influence upon of observable behaviors in
       contexts together comprising centers of attention, enabling us
       to achieve the distinctively human feat of open-ended joint
       agency by coordinating these parameters specifying centers of
       attention governing their respective processes of semiotic
       self-control.

     + **The collaborative constitution of agency hypothesis.** I
       propose based on confluences of convergent evidence that the
       origin of humans explicitly using abstract symbols to scaffold
       joint attention is directly derived from coordinating and
       generalizing task structure. Tacitly in basic agency and
       explicitly in joint agency, it is the compression of focus into
       subtasks that produces generality.  Further, the use of
       manifest public sign vehicles to invoke centers of attention
       makes joint agency significantly more capable than basic
       agency, as it allows for developing explicit and particular
       strategies of attention to structuring of the focus of centers.

     + **Joint agency solves the hard problem of content.** In
       agreement with Hutto & Myin's proposal with respect to the
       function of public symbol systems, I claim that joint
       attention, by making symbolic abstraction and the collaborative
       development of symbol creating joint agency, solves the hard
       problem of content.

     + **Human semiotic task abstraction appears is Turing complete**
       whereas solo animal task abstraction is not, which agrees with
       the plainly obvious fact of the enormous generative variety of
       the human niche vs that of other animals.  Importantly, this
       Turing completeness is a symptom of content-curating practices
       owing to capacities for meta-level use of symbol in
       constituting symbol, not its cause.

   + **FoCo & CoFoCo: a Formal Ecological-Semiotic Model of Agency and
     Joint Agency** Formally explicate the notion of focus compression
     (FoCo) for basic agency and of coordinated focus compression
     (CoFoCo) for joint agency.

   + **Testing the Hypothesis**

     + **FoCo should improve unsupervised artificial agent performance
       on standard benchmarks.** These conclusions apply to the hard
       problem of content in computing, suggesting a constructive test
       of the hypothesis, that artificial agents should benefit from
       implementing a FoCo strategy for acquiring compressed attention
       to centers as modeled in the way proposed here.

     + **CoFoCo should create greater improvements than FoCo alone.**
       Following up on the promising results of Lee et al (2021), a
       second constructive test of the hypothesis is proposed that
       artifical agents trained using a CoFoCo strategy of coordinated
       attention to centers as modeled here, will considerably improve
       performance on tasks.

     + **CoFoCo should enable augmentation of human agency by aligning
       agents with human centers**. A third constructive test of the
       hypothesis is proposed that bears on the human and the machine
       case in tandem: human decisions in contexts of engagement,
       focus, and support which together describe centers of attention
       can be instrumented enabling data collection and training using
       the CoFoCo strategy such that machine agents can offer some
       degree of awareness and support in shared contexts of
       scaffolding human practice.

** Ecological Information Basics

*** Why ecological psychology?

    In the second half of the 20th century, James and Eleanor Gibson
    began the project of developing a phenomenology of perception as
    prospective biological control guided by affordances of the
    physical environment.  Rejecting the Cartesian view of perception
    being the result of enriching raw sensory input, they arrived at a
    theory of perceptual development consistent with the biological
    understanding of development as differentiation, and of perceptual
    control systems rather than sensations.  This work produced a
    comprehensive theory of information in terms of the direct fit
    between agents and law-based dispositions of the environment.

    TODO, make case for eco psych over other approaches

*** Law-based ecological information

    The ecological approach has developed a powerfully explanatory
    account of information pick-up as a fit between organisms and
    their environments.  Invariant physical patterns, such as
    regularities in the array of light reflecting upon surfaces over
    perspectival movement at the relevant scale, can specify
    affordances.  Affordances, such as a walkable ground, or a
    climbable tree, specify reliable options to be realized by agents
    that are able to use them.  Effectivities, which are the
    dispositional properties of agents that complement affordances,
    can be innately evolved to fit affordances or require
    differentiation in the course of development to realize the
    affordances they fit.  In ecological psychology the term "task"
    refers to instances of prospective control-oriented behavior,
    which is understood to characterize the teleological nature of
    agents' behavior in general.  When an agent actively engaged in a
    task uses affordances to guide itself toward a preferable state,
    it is picking up on ecological information.  Embodiment of
    ecological information is the calibration of body and environment
    in a kind of measured adjustment guided by affordance.  To acquire
    the information supporting perception-action in this way is to
    measure affordances by the effectivities that fit them.

*** Convention-based ecological information

    Affordances have the unique property of supporting direct
    perception by specifying reliable action opportunities for
    compatible and prepared agents, but direct perception is not the
    only way for agents to acquire ecological information.  Agents
    also come to embody ecological information by indirect,
    convention-based means as well (Golonka 2015).  Convention-based
    information, unlike law-based information, does not guide action,
    but rather selects, or tips the balance between attending among
    available affordances of the environment.  An example that serves
    well to elucidate why is that the exterior of a can of beer does
    not specify the information for getting to the outcome of drinking
    beer in the same way that the reflectivity of a paved surface
    specifies the information for slipping and sliding on ice, or the
    way that the can affords opening by lifting its lever.  Instead
    what the labeling of the can offers is a way of selecting the beer
    drinking experience, which is then engaged via direct affordances
    of the can and the liquid.  This account of the use of conventions
    to selectively attend to the direct affordances that must be
    realized in order to achieve the indicated outcome illustrates
    that some actionable/perceivable event or feature (eg. a stop sign
    as object in the layout of the environment) is always needed as a
    means of selecting some other (eg. controlling one's vehicle in
    relation to the expected behavior of other cars.)

    As Golonka's examples illustrate, the convention-based/law-based
    distinction is a cross-cutting one, orthogonal to distinctions
    such as natural versus human-made or social versus nonsocial.  The
    most widely popularized examples of law-based information tend to
    be natural, non-social examples (such as the affordances of
    climbable trees to animals that can climb them), but this is
    mainly for pedagogical reasons due to their relative simplicity.
    There are human-made, non-social affordances such as steps, ramps,
    doorways, walkways, and shelters, and natural social affordances
    such as infant crying and facial expressions, and pointing
    gestures, which we will explore in more detail.  Most social
    information is however convention-based, both among humans and
    animal species.  Golonka gives the example of the honeybee waggle
    dance, which might seem to be a social affordance supporting an
    ecological law relationship between honeybees and food sources,
    but is recognized instead as convention-based natural social
    information because the conditions it is sensitive to may blink in
    and out of existence.  Human gaze-following in contrast is a
    natural social affordance, because gaze is used in cooperative
    communication, and it always follows linearly to the immediate
    location of its target.  For comparison, the human deictic
    convention of composing phrases such as "the room we are in" is
    conventional, because it can't be used to continuously guide
    action as a mathematically expressible ecological law the way that
    gaze can.  And finally, it should be clarified that despite the
    wealth of socially-oriented examples, convention-based information
    need not be social, as demonstrated by examples such as a domestic
    cat relying (often unsuccessfully) on the sound of a can-opener to
    pursue an opportunity for food, or a person deciding between two
    courses of action based on the outcome of a coin flip.

** An Ecological-Semiotic Approach to Perception and Information
*** Gibsonian information theory needs Peircean biosemiotics
*** Peircean biosemiotics needs a Gibsonian foundation
*** Semiotic scaffolding
*** The prospective control task as semiotic self-control
** The Hard Problem of Content
*** The problem
*** Proposed solutions
*** Joint attention as a solution to the hard problem of content

**** Tomasello's theory of cooperative commmunication

     Research on joint attention in primates and human infants has
     uncovered a framework of cooperative communication unique to
     humans: at around 9 months of age, we begin to use gestural
     signals to share, follow into, and direct what adults attend to
     (Carpenter, Nagell, Tomasello 1998, Tomasello 2008). These skills
     suggest an innate disposition to assist others by guiding
     attentional focus as an effective means toward shared objectives.
     These behaviors, especially when augmented by tools and
     repeatable practices for motivating and guiding attention, are
     referred to as scaffolding.  This framework of cooperative
     communication has received wide attention as an explanation of
     the origin and present source of the unique human niche,
     characterized by the ubiquitous exchange of shared intentional
     practices and narratively curated content.

** An Ecological-Semiotic Approach to Joint Attention
*** Clues from empirical research
*** The collaborative constitution of agency hypothesis
*** Joint agency solves the hard problem of content
*** Human semiotic task abstraction is Turing complete
** FoCo & CoFoCo: a Formal Ecological-Semiotic Model of Agency and Joint Agency
** Testing the Hypothesis
*** FoCo should improve unsupervised artificial agent performance on standard benchmarks
*** CoFoCo should create greater improvements than FoCo alone
*** CoFoCo should enable augmentation of human agency by aligning agents with human centers


** References

   + "Philosophical Investigations" Wittgenstein 1953
     https://static1.squarespace.com/static/54889e73e4b0a2c1f9891289/t/564b61a4e4b04eca59c4d232/1447780772744/Ludwig.Wittgenstein.-.Philosophical.Investigations.pdf
   + "Man-Computer Symbiosis" Licklider 1960
     http://worrydream.com/refs/Licklider%20-%20Man-Computer%20Symbiosis.pdf
   + "Augmenting Human Intellect: A Conceptual Framework" Engelbart
     1962 http://dougengelbart.org/content/view/138
   + "The Senses Considered as Perceptual Systems" Gibson 1966
     https://b-ok.cc/book/3554998/9b8962
   + "The Ecological Approach to Visual Perception" Gibson 1979
     http://b-ok.cc/book/864226/e0dd92
   + "Affordances and Prospective Control: An Outline of the Ontology"
     Turvey 1992
     https://canvas.brown.edu/courses/755816/files/20990546/download?wrap=1
   + "Social cognition, joint attention, and communicative competence
     from 9 to 15 months of age."  Carpenter, Nagell, Tomasello 1998
     http://booksc.xyz/book/15451904/9e3c39
   + "An Ecological Approach to Perceptual Learning and Development"
     Gibson & Pick 2000 https://b-ok.cc/book/879525/7d1f69
   + "Origins of Human Communication" Tomasello 2008
     http://b-ok.cc/book/541274/39859f
   + "Empowerment: A Universal Agent-Centric Measure of Control"
     Klyubin, Polani, Nehaniv 2005
     https://www.researchgate.net/publication/4201381_Empowerment_A_Universal_Agent-Centric_Measure_of_Control
   + "A free energy principle for the brain" Friston, Kilner, Harrison
     2006
     https://www.fil.ion.ucl.ac.uk/~karl/A%20free%20energy%20principle%20for%20the%20brain.pdf
   + "On Intelligence From First Principles: Guidelines for Inquiry
     Into the Hypothesis of Physical Intelligence (PI)" Turvey &
     Carello 2012 https://booksc.xyz/book/42939095/6bac90
   + "The Evolution of Semiotic Self-Control" Frederik Stjernfelt 2012
     https://www.researchgate.net/profile/Frederik-Stjernfelt-2
   + "Radicalizing Enactivism" Hutto & Myin 2013
     http://b-ok.cc/book/2554656/1b7ea8
   + "Natural Propositions" Frederik Stjernfelt 2014
     https://books.google.com/books/about/Natural_Propositions.html?id=X37ioQEACAAJ
   + "A Rich Landscape of Affordances" Rietveld & Kiverstein 2014
     https://www.tandfonline.com/doi/full/10.1080/10407413.2014.958035?scroll=top&needAccess=true
   + "Self-organization, free energy minimization, and optimal grip on
     a field of affordances" Bruineberg & Rietveld 2014
     https://www.frontiersin.org/articles/10.3389/fnhum.2014.00599/full
   + "Laws and Conventions in Language-Related Behaviors" Golonka 2015
     http://booksc.xyz/book/50082310/1e8631
   + "Strange Tools: Art and Human Nature" Noë 2015
     http://b-ok.cc/book/2640649/b1b44d
   + "Cultural Affordances: Scaffolding Local Worlds Through Shared
     Intentionality and Regimes of Attention" Ramstead, Veissière,
     Kirmayer 2016
     https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4960915/
   + "Evolving Enactivism" Hutto & Myin 2017
     http://b-ok.cc/book/2947353/09d772
   + "Attentional actions – an ecological-enactive account of
     utterances of concrete words" Jasper C. Van Den Herik 2018
     https://sciendo.com/article/10.2478/plc-2018-0005
   + "Free energy, empowerment, and predictive information compared"
     Biehl, Guckelsberger, Salge, Smith, Polani 2018
     https://www.mis.mpg.de/fileadmin/pdf/abstract_gso18_3300.pdf
   + "Getting into predictive processing’s great guessing game:
     Bootstrap heaven or hell?" Hutto 2018
     https://philpapers.org/rec/HUTGIP
   + "Steps to an Ecology of Bicycles for the Mind: A Situated
     Programming Manifesto" Levy 2018
     http://senters.info/situated-programming
   + "Unsupervised learning and the natural origins of content" Korbak
     2019 http://philsci-archive.pitt.edu/16429/
   + "Joint Attention for Multi-Agent Coordination and Social
     Learning" Dennis Lee, Natasha Jaques, Chase Kew, Douglas Eck,
     Dale Schuurmans, Aleksandra Faust 2021
     https://arxiv.org/abs/2104.07750?context=cs.MA
